[phases.setup]
nixPkgs = ["...", "python311", "gcc"]
aptPkgs = ["...", "python3-pip", "python3-venv"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "python3 -m venv /opt/venv",
    ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[start]
cmd = ". /opt/venv/bin/activate && cd mmm-platform/backend && uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"