[phases.setup]
nixPkgs = ["...", "python311", "gcc"]

[phases.install]
cmds = ["cd mmm-platform/backend && pip install -r requirements.txt"]

[start]
cmd = "cd mmm-platform/backend && uvicorn main:app --host 0.0.0.0 --port $PORT"