version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: mmm_user
      POSTGRES_PASSWORD: mmm_password
      POSTGRES_DB: mmm_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://mmm_user:mmm_password@postgres:5432/mmm_db
      REDIS_URL: redis://redis:6379
      SECRET_KEY: your-secret-key-here
      ENVIRONMENT: development
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
    command: python main.py

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start

volumes:
  postgres_data: